parameters:
    banned_words:
        - cambio
        - compro
        - compró
        - conpro
        - comprando
        - comprar
        - busco
        - euro
        - euros
        - peso
        - pesos
        - mexicanos
        - mxn
        - canadiense
        - canadienses
        - envia
        - envía
        - enviamos
        - enviale
        - envio
        - envío
        - necesito
        - nesecita
        - nesecito
        - libra
        - esterlina
        - entrego
        - entrega
        - doy
        - remesa
        - remesas
        - remesass
        - transfiero
        - transferencia
        - transferecia
        - tarjeta
        - tarjetas
        - credito
        - depósito
        - deposito
        - pago
        - pagamos
        - recarga
        - recargo
        - recargamos
        - mlc